/* =========================================================================
   Icon registry — maps the original `data-lucide="…"` names to lucide-react
   components so data-driven tabs can keep referencing icons by string.
   ========================================================================= */
import {
  AlertTriangle,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  CalendarClock,
  Check,
  CheckCircle2,
  Clapperboard,
  Coins,
  CreditCard,
  DatabaseBackup,
  Download,
  Eye,
  EyeOff,
  Film,
  Flag,
  History,
  Hourglass,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  MousePointerClick,
  Pause,
  PauseCircle,
  Pencil,
  Percent,
  Play,
  Plus,
  Repeat,
  RotateCcw,
  Save,
  ScrollText,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Star,
  StarOff,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  UploadCloud,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Video,
  X,
  XCircle,
} from 'lucide-react'

export const ICONS = {
  'alert-triangle': AlertTriangle,
  'badge-check': BadgeCheck,
  ban: Ban,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'calendar-clock': CalendarClock,
  check: Check,
  'check-circle-2': CheckCircle2,
  clapperboard: Clapperboard,
  coins: Coins,
  'credit-card': CreditCard,
  'database-backup': DatabaseBackup,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  film: Film,
  flag: Flag,
  history: History,
  hourglass: Hourglass,
  'key-round': KeyRound,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  megaphone: Megaphone,
  menu: Menu,
  'mouse-pointer-click': MousePointerClick,
  pause: Pause,
  'pause-circle': PauseCircle,
  pencil: Pencil,
  percent: Percent,
  play: Play,
  plus: Plus,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  save: Save,
  'scroll-text': ScrollText,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  star: Star,
  'star-off': StarOff,
  ticket: Ticket,
  timer: Timer,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'upload-cloud': UploadCloud,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  video: Video,
  x: X,
  'x-circle': XCircle,
}

/** <Icon name="banknote" /> — renders nothing for unknown names. */
export default function Icon({ name, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp {...rest} />
}
