const pw = await import(process.env.PLAYWRIGHT_MODULE)
const b = await pw.chromium.launch(); const page = await (await b.newContext({ ...pw.devices['Pixel 7'] })).newPage()
await page.goto(`${process.env.BASE}/`, { waitUntil: 'domcontentloaded' }); await page.waitForTimeout(2500)
const burger = page.locator('button.hamburger')
console.log('hamburger count/visible:', await burger.count(), await burger.first().isVisible())
await burger.first().click(); await page.waitForTimeout(1000)
const menu = await page.evaluate(() => { const m = document.querySelector('.mobile-menu'); return { cls: m?.className, items: [...(m?.querySelectorAll('a, button') || [])].map((x) => `${x.tagName}:${x.getAttribute('href') || ''}:${x.innerText.trim()}`) } })
console.log(JSON.stringify(menu))
const link = page.locator('.mobile-menu.open a[href="/creator-capital"], .mobile-menu.open button:has-text("Creator Capital")').first()
console.log('Creator Capital visible in open menu:', await link.isVisible().catch(() => false))
await link.click(); await page.waitForTimeout(2000); console.log('after tap:', new URL(page.url()).pathname)
await page.screenshot({ path: `${process.env.AUD}/F11-mobile-menu.png` })
await b.close()
