/* =========================================================================
   Icon registry — maps the original `data-lucide="…"` names to lucide-react
   components so data-driven sections can keep using string icon names.
   ========================================================================= */
import {
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  Clapperboard,
  Clock,
  Coins,
  Compass,
  Crown,
  Download,
  Eye,
  EyeOff,
  Facebook,
  Flame,
  Gem,
  HandCoins,
  Hourglass,
  Infinity as InfinityIcon,
  Info,
  Instagram,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Link as LinkIcon,
  Link2,
  Lock,
  LockKeyhole,
  MonitorPlay,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Megaphone,
  Menu,
  MessageCircle,
  Music2,
  Pause,
  Percent,
  Play,
  PlayCircle,
  Plus,
  Receipt,
  RefreshCcw,
  Rocket,
  Route as RouteIcon,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Smartphone,
  SmartphoneNfc,
  Sparkles,
  Star,
  Tag,
  Ticket,
  Timer,
  TrendingUp,
  Type,
  Upload,
  UploadCloud,
  User,
  UserCog,
  UserPlus,
  Video,
  Volume2,
  Users,
  Wallet,
  X,
  XCircle,
  Youtube,
  Zap,
} from 'lucide-react'

export const ICONS = {
  'align-left': AlignLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  check: Check,
  'check-circle-2': CheckCircle2,
  clapperboard: Clapperboard,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  crown: Crown,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  facebook: Facebook,
  flame: Flame,
  gem: Gem,
  'hand-coins': HandCoins,
  hourglass: Hourglass,
  infinity: InfinityIcon,
  info: Info,
  instagram: Instagram,
  'key-round': KeyRound,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  library: Library,
  link: LinkIcon,
  'link-2': Link2,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'monitor-play': MonitorPlay,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  maximize: Maximize,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  'music-2': Music2,
  pause: Pause,
  percent: Percent,
  play: Play,
  'play-circle': PlayCircle,
  plus: Plus,
  receipt: Receipt,
  'refresh-ccw': RefreshCcw,
  rocket: Rocket,
  route: RouteIcon,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  'smartphone-nfc': SmartphoneNfc,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  ticket: Ticket,
  timer: Timer,
  'trending-up': TrendingUp,
  type: Type,
  upload: Upload,
  'upload-cloud': UploadCloud,
  user: User,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  video: Video,
  'volume-2': Volume2,
  users: Users,
  wallet: Wallet,
  x: X,
  'x-circle': XCircle,
  youtube: Youtube,
  zap: Zap,
}

/** <Icon name="play-circle" /> — renders nothing (silently) for unknown names. */
export default function Icon({ name, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp {...rest} />
}
